before:
  hooks:
    - 'go mod tidy'
    - 'go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo@latest'
    - 'goversioninfo -platform-specific -ver-major="{{ .Major }}" -product-ver-major="{{ .Major }}" -ver-minor="{{ .Minor }}" -product-ver-minor="{{ .Minor }}" -ver-patch="{{ .Patch }}" -product-ver-patch="{{ .Patch }}" -file-version="{{ .Version }} ({{ .ShortCommit }})" -product-version="{{ .Version }} ({{ .ShortCommit }})"'

builds:
  - id: with-upx
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    flags:
      - -trimpath
    ldflags:
      - '-s -w'
      - '-X main.version={{ .Version }}'
      - '-X main.commit={{ .ShortCommit }}'
    hooks:
      post: 'upx --lzma {{ .Path }}'
  - id: without-upx
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    flags:
      - -trimpath
    ldflags:
      - '-s -w'
      - '-X main.version={{ .Version }}'
      - '-X main.commit={{ .ShortCommit }}'

archives:
  - format: tar.gz
    replacements:
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files: [none*]

changelog:
  filters:
    exclude:
      - '^chore'
      - '^docs'
      - '^refactor'
      - '^style'
      - '^test'
