before:
  hooks:
    - 'go mod tidy'
    - 'go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo@latest'
    - './.goreleaser-before.sh "{{.Major}}" "{{.Minor}}" "{{.Patch}}" "{{.ShortCommit}}"'

builds:
  - id: with-upx
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    main: ./cmd/ayd
    flags:
      - -trimpath
    ldflags:
      - '-s -w'
      - '-X main.version={{ .Version }}'
      - '-X main.commit={{ .ShortCommit }}'
    hooks:
      post: 'upx --lzma {{ .Path }}'
  - id: without-upx
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    main: ./cmd/ayd
    flags:
      - -trimpath
    ldflags:
      - '-s -w'
      - '-X main.version={{ .Version }}'
      - '-X main.commit={{ .ShortCommit }}'

archives:
  - format: tar.gz
    replacements:
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files: [none*]

changelog:
  filters:
    exclude:
      - '^chore'
      - '^docs'
      - '^refactor'
      - '^style'
      - '^test'
