before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - '-s -w'
      - '-X main.version={{ .Version }}'
      - '-X main.commit={{ .ShortCommit }}'

archives:
  - format: binary
    replacements:
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files: [none*]

changelog:
  filters:
    exclude:
      - '^chore'
      - '^docs'
      - '^refactor'
      - '^style'
      - '^test'
