before:
  hooks:
    - 'go mod tidy'
    - 'go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo@latest'
    - './.goreleaser-before.sh "{{.Major}}" "{{.Minor}}" "{{.Patch}}" "{{.ShortCommit}}"'

builds:
  - id: with-upx
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    main: ./cmd/ayd
    flags:
      - -trimpath
    ldflags:
      - '-s -w'
      - '-X main.version={{ .Version }}'
      - '-X main.commit={{ .ShortCommit }}'
    hooks:
      post: 'upx-ucl --lzma {{ .Path }}'
  - id: without-upx
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
    main: ./cmd/ayd
    flags:
      - -trimpath
    ldflags:
      - '-s -w'
      - '-X main.version={{ .Version }}'
      - '-X main.commit={{ .ShortCommit }}'

archives:
  - format: tar.gz
    name_template: >-
      {{- .ProjectName -}}
      _
      {{- .Version -}}
      _
      {{- .Os -}}
      _
      {{- if eq .Arch "386" -}}
        i386
      {{- else if eq .Arch "amd64" -}}
        x86_64
      {{- else -}}
        {{- .Arch -}}
      {{- end -}}
    format_overrides:
      - goos: windows
        format: zip
    files: [none*]

changelog:
  filters:
    exclude:
      - '^chore'
      - '^docs'
      - '^refactor'
      - '^style'
      - '^test'
