#!/bin/sh

if [ "$1" = "plug:change" ]; then
    echo '{"time":"2001-02-03T16:05:06Z","status":"HEALTHY","latency":123.456,"target":"changed:plug","message":"check changed:plug"}'
elif [ "$1" != "plug:empty" ]; then
    echo '{"time":"2001-02-03T16:05:06Z","status":"HEALTHY","latency":123.456,"target":"'${1}'","message":"check '${1}'"}'
fi

if [ "$1" = "plug:invalid-record" ]; then
    echo "this is invalid"
fi

# test empty line
echo
