#!/bin/sh

if [ "$7" = "" ]; then
    echo '{"time":"2001-02-03T16:05:06Z","status":"HEALTHY","latency":123.456,"target":"'$1'","message":"\"'$1,$2,$3,$4,$5,$6'\""}'
else
    echo '{"time":"2001-02-03T16:05:06Z","status":"HEALTHY","latency":123.456,"target":"'$1'","message":"\"'$1,$2,$3,$4,$5,$6'\"","extras":'"$7"'}'
fi
